/*
Title: Filter With IN and NOT IN
Difficulty: Beginner

Concepts:
- IN
- NOT IN
- Multi-value filters

Learning objectives:
- Match one value from a list with IN.
- Exclude values with NOT IN.
- Write readable status and city filters.

Problem statement:
The fulfilment team wants paid or shipped orders, but not orders shipping to
London.

SQL solution:
*/

SELECT
    id,
    status,
    order_date,
    shipping_city
FROM orders
WHERE status IN ('paid', 'shipped')
    AND shipping_city NOT IN ('London')
ORDER BY order_date ASC;

/*
Explanation:
IN checks whether a value appears in a list. NOT IN excludes values in a list.
This query keeps paid or shipped orders unless the shipping city is London.

Expected results:
The query returns the shipped Birmingham order and the paid Cardiff and
Manchester orders.

Real-world example:
An operations queue might include orders in workable statuses while excluding a
region handled by a different team.

Performance notes:
Short IN lists are easy to read and usually fine. Be careful with very large
lists generated by application code.

Common mistakes:
- Forgetting quotes around text values.
- Using NOT IN with nullable values without understanding NULL behaviour.
- Replacing clear IN lists with long chains of OR conditions.

Challenge exercise:
Find card or PayPal payments that are not refunded or failed.

Challenge solution:
*/

SELECT
    id,
    order_id,
    amount,
    payment_method,
    status
FROM payments
WHERE payment_method IN ('card', 'paypal')
    AND status NOT IN ('refunded', 'failed')
ORDER BY amount DESC;

/*
Related examples:
- ../01_basic_queries/10_in.sql
- 02_where_or.sql
- 08_null_handling.sql
*/
